- README.md
- public/index.html
> Fix HTTPS vs. HTTP for textbox.io

- README.md
- public/index.html
Thanks for the awesome work! Made it easy to add emojis.
> Add ReadMe.io

- README.md
- public/index.html
Thanks for such a great resource!
> Added groups.io

- public/index.html
Hi - Looks like this was three sounds behind! I've updated them & now the whole world can hold onto its collective butt.
> Three new sounds in Campfire

- README.md
- public/index.html
[TeamworkChat](http://www.teamwork.com/chat)
> Added TeamworkChat to "supported by" list

- public/index.html
I added some synonyms by using the `data-alternative-name`-attribute.
Includes:
* animal
* bird
* water
* magnifying, glass
* sport
* box
* christmas
* clock
* light
* calendar
* cards
* vehicle
* tools
* money
> Some synonyms

- README.md
All of them are available on npm
> Tweak JavaScript section

- README.md
- public/index.html
https://sdelements.github.io/lets-chat
> Added Let's Chat

- README.md
If you want us, you can have us. Thank you for your fine work!
> add igdb to emoji users

- public/index.html
Added data-alternative-name "Happy" to:
- smile; 
- smiley; 
- sweat_smile; 
- smiley_cat
- smile_cat.
Added data-alternative-name "Relief" to:
- sweat_smile.
> Added data-alternative-name "Happy" and "Relief" to some smile emojis

- README.md
> Added changes to Readme

- public/index.html
:japanese_ogre: :japanese_goblin:
> Add aliases for Japanese goblins (`⊇`)

- public/index.html
> Add aliases for running is a sport

- public/index.html
:hearts: :spades: :clubs: :diamonds:
> Add aliases for card suit

- public/index.html
:cherry_blossom: :tulip: :rose: :sunflower: :hibiscus: :flower_playing_cards: :white_flower:
> Add aliases for floral objects

- README.md
> Update and freeze the example link to `data-alternative-name`

- public/style.css
Hello,
As I see there is a horizontal scroll if you check the site on the mobile devices.
So I applied some changes to the styles.
Please let me know if that makes sense.
Thanks
> Prevent horizontal scrolling on mobile devices

- public/index.html
> Add an alias for fish_cake that called "Naruto" in Japan

- README.md
- public/index.html
[Gitter](https://gitter.im/) :sparkles: 
Appended to list in `README.md` and `public/index.html`
> Add Gitter to list of emoji supporting apps

- public/index.html
> Added two alternatives for fearful

- public/index.html
> Added a few alternative names

- public/index.html
> Synonym 8ball>magic_ball

- public/index.html
added 'television' as alternative name for 'tv'
> alternative name television

- README.md
> Update README.md, minor grammar fix

- public/index.html
Please don't hurt me.  I'm new.
> Added synonyms for sound

- public/index.html
> moresynonyms

- public/index.html
Who doesn't love food? Now foodies can rejoice and have easier access to food-related emojis!!
> Added miscellaneous food-related tags

- public/index.html
> Add more synonyms

- public/index.html
> Added alternative name

- public/index.html
> Old man/woman

- public/index.html
I'm always associated with this rolling. :smile:
See if it sounds okay.
> Add synonym for eyes: eye-rolling

- public/index.html
> cold_sweat

- public/index.html
YouTube added this in their chat function for live streams.
> added YouTube

- public/index.html
The 8ball is listed twice!
Maybe there's supposed to be some other sport ball that goes here, I'm not sure.
> Remove duplicate 8ball declaration

- public/index.html
I wrote a small script that pulls a json file from this repo (https://github.com/muan/emojilib) and adds the keywords to the emojis if they don't have them already and this is the result!
> Added a ton of alternative names/keywords from the emojilib repo

- public/index.html
Morfy also uses emoji as plugin
> Added Morfy to public/index.html

- README.md
- public/index.html
Keep this on hold, it may re-open. But, merge for now.
> plug.dj shut down

- public/index.html
@arvida adding heart to `data-alternative-name` for:
- :heart_eyes:
- :kissing_heart:
- :yellow_heart:
- :purple_heart:
- :blue_heart:
- :heart:
- :green_heart:
- :broken_heart:
- :heartbeat:
- :heartpulse:
- :two_hearts:
- :revolving_hearts:
- :sparkling_heart:
- :couple_with_heart:
- :heart_eyes_cat:
- :gift_heart:
- :hearts:
- :heart_decoration:
> Add data alternative name

- README.md
- public/index.html
Adds [Habitica](https://habitica.com) to the list of pages.
Closes #336.
> Add habitica to pages list

- public/index.html
Synonyms added to emojis located in the "Places" section
> Added synonyms in Index

- README.md
It works like this
```swift
Emoji.flag("NO") // 🇳🇴
Emoji.standardName("😁") // GRINNING FACE WITH SMILING EYES
Emoji.search(["GRINNING"]) // ["😁", "😸"]
Emoji.list()
```
> Add Emoji in Omnia

- README.md
Add [twemoji](https://github.com/jollygoodcode/twemoji) gem for Ruby application.
> Add https://github.com/jollygoodcode/twemoji

- README.md
I rewrite it to be more swifty, using GitHub database
> Update Swift library

- README.md
- public/index.html
Yet another site to add, supporting emoji in comments and checklist items.
> Add Kanban Tool to the list of sites supporting Emoji.

- public/index.html
The GitHub star and fork buttons aren't working (404).
> Fix username for GitHub button

- README.md
the repository no longer exists and was deleted by @frissdiegurke
> Removed a link as Repository no longer exists

- public/index.html
The names of the three wise monkeys are Mizaru (see no evil), Kikazaru
(hear no evil) and Iwazaru (speak no evil). They are sometimes given as
Mizaru, Mikazaru and Mazaru.
Source: https://en.wikipedia.org/wiki/Three_wise_monkeys
> Add names of the three wise monkeys

- public/index.html
Bathtub: tub
Books: book
Shoe: foot, fashion, white
Removed redundant "food" names in eggs and bread
> Added alternative names

- gssdg
- public/index.html
alternative name changed at line 150 of grimacing to mental and emotional.
> Alternative named changed at line 150 of index.html

- public/index.html
> New synonym

- public/index.html
Made trumpet an instrument too
> Trumpet = Instrument

- public/index.html
Two emoji missing when using natural language searching for flowers
> Plural for flowers added

- public/index.html
train2.png = "public"
bullettrain_side.png = bullettrain_front.png
> Additional alternative names

- public/index.html
This commit adds the alternative name forest to :evergreen_tree: and :deciduous_tree:
> 2 new alternative names
